ALTER SESSION SET container = XEPDB1;
CREATE TABLE PUBLICATIONS.INVESTMENTS (
    id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    id_user VARCHAR2(36) NOT NULL,
    id_publication NUMBER NOT NULL,
    amount NUMBER NOT NULL,
    token VARCHAR2(200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    FOREIGN KEY (id_publication) REFERENCES PUBLICATIONS.PUBLICATIONS(id),
    FOREIGN KEY (id_user) REFERENCES PUBLICATIONS.USERS(id)
);