ALTER SESSION SET container = XEPDB1;
CREATE TABLE PUBLICATIONS.PUBLICATIONS_CATEGORIES (
    id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    id_publication NUMBER NOT NULL,
    id_category NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    FOREIGN KEY (id_publication) REFERENCES PUBLICATIONS.PUBLICATIONS(id),
    FOREIGN KEY (id_category) REFERENCES PUBLICATIONS.CATEGORIES(id)
);